.TH "Beam" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Beam \- 
.PP
The beam which the wheels are attached to and which the belt runs along\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Conveyor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBeam\fP (b2Vec2 p1, b2Vec2 p2, float32 width, int cmBits, b2World *world)"
.br
.ti -1c
.RI "b2Vec2 & \fBgetLocalAnchor1\fP ()"
.br
.ti -1c
.RI "b2Vec2 & \fBgetLocalAnchor2\fP ()"
.br
.ti -1c
.RI "b2Body * \fBgetBody\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "b2Body * \fBm_body\fP"
.br
.ti -1c
.RI "b2Vec2 \fBm_localAnchor1\fP"
.br
.ti -1c
.RI "b2Vec2 \fBm_localAnchor2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The beam which the wheels are attached to and which the belt runs along\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Beam::Beam (b2Vec2p1, b2Vec2p2, float32width, intcmBits, b2World *world)"

.SH "Member Function Documentation"
.PP 
.SS "b2Body* Beam::getBody ()\fC [inline]\fP"

.SS "b2Vec2& Beam::getLocalAnchor1 ()\fC [inline]\fP"

.SS "b2Vec2& Beam::getLocalAnchor2 ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "b2Body* Beam::m_body\fC [private]\fP"

.SS "b2Vec2 Beam::m_localAnchor1\fC [private]\fP"

.SS "b2Vec2 Beam::m_localAnchor2\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
