.TH "CommandSequenceInterpreter.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandSequenceInterpreter.h \- 
.PP
Contains the CommandSequanceInterpreter-class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Actuators\&.h'\fP
.br
\fC#include 'Sensors\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommandSequenceInterpreter\fP"
.br
.RI "\fIUse keyboard- or terminal-input to control the actuator- and sensor-sets\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains the CommandSequanceInterpreter-class\&. 

\fBAuthor:\fP
.RS 4
Roy Kollen Svendsen 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
