.TH "Communicator.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Communicator.h \- 
.PP
Contains the Communicator-class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <boost/system/error_code\&.hpp>\fP
.br
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include <boost/thread\&.hpp>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommunicator\fP"
.br
.RI "\fIRead frowm and write to an arbitrary serial-port\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains the Communicator-class\&. 

\fBAuthor:\fP
.RS 4
Roy Kollen Svendsen 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
