.TH "ContactPoint" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContactPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimulatorPage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "b2Fixture * \fBfixtureA\fP"
.br
.ti -1c
.RI "b2Fixture * \fBfixtureB\fP"
.br
.ti -1c
.RI "b2Vec2 \fBnormal\fP"
.br
.ti -1c
.RI "b2Vec2 \fBposition\fP"
.br
.ti -1c
.RI "b2PointState \fBstate\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "b2Fixture* ContactPoint::fixtureA"

.SS "b2Fixture* ContactPoint::fixtureB"

.SS "b2Vec2 ContactPoint::normal"

.SS "b2Vec2 ContactPoint::position"

.SS "b2PointState ContactPoint::state"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
