.TH "ConveyorBeltShield" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConveyorBeltShield \- 
.PP
Hinder the conveyorbelt in falling off\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Conveyor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConveyorBeltShield\fP (b2Vec2 p1, b2Vec2 p2, float32 beamThickness, float32 beltThickness, int cmBits, b2World *world)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "b2Vec2 \fBm_p1\fP"
.br
.ti -1c
.RI "b2Vec2 \fBm_p2\fP"
.br
.ti -1c
.RI "float32 \fBm_beamThickness\fP"
.br
.ti -1c
.RI "float32 \fBm_beltThickness\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Hinder the conveyorbelt in falling off\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConveyorBeltShield::ConveyorBeltShield (b2Vec2p1, b2Vec2p2, float32beamThickness, float32beltThickness, intcmBits, b2World *world)"

.SH "Member Data Documentation"
.PP 
.SS "float32 ConveyorBeltShield::m_beamThickness"

.SS "float32 ConveyorBeltShield::m_beltThickness"

.SS "b2Vec2 ConveyorBeltShield::m_p1"

.SS "b2Vec2 ConveyorBeltShield::m_p2"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
