.TH "ConveyorSynchronizer.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConveyorSynchronizer.h \- 
.PP
Contains the class which synchronize conveyors\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Conveyor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConveyorSynchronizer\fP"
.br
.RI "\fISynchronize Conveyors\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains the class which synchronize conveyors\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
