.TH "Conveyor.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Conveyor.h \- 
.PP
Contains the Conveyor-class and the classes needed to build it\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Sensors\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWheel\fP"
.br
.RI "\fIThe conveyors wheels\&. \fP"
.ti -1c
.RI "class \fBBeam\fP"
.br
.RI "\fIThe beam which the wheels are attached to and which the belt runs along\&. \fP"
.ti -1c
.RI "class \fBConveyorBelt\fP"
.br
.RI "\fIThe conveyorbelt\&. \fP"
.ti -1c
.RI "class \fBConveyorBeltShield\fP"
.br
.RI "\fIHinder the conveyorbelt in falling off\&. \fP"
.ti -1c
.RI "class \fBConveyor\fP"
.br
.RI "\fIAssemble the conveyor and expose an interface through which controlling the conveyor is possible\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBt_medbringerType\fP { \fBingen\fP, \fBknott\fP, \fBkrok\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the Conveyor-class and the classes needed to build it\&. 

\fBAuthor:\fP
.RS 4
Roy Kollen Svendsen 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBt_medbringerType\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIingen \fP\fP
.TP
\fB\fIknott \fP\fP
.TP
\fB\fIkrok \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
