.TH "ConveyorSynchronizer.cpp" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConveyorSynchronizer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ConveyorSynchronizer\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
