.TH "ConveyorActuatorBinary" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConveyorActuatorBinary \- 
.PP
Turn a conveyor ON or OFF\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Actuators\&.h>\fP
.PP
Inherits \fBConveyorActuator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConveyorActuatorBinary\fP (int id, \fBConveyor\fP *conveyor)"
.br
.ti -1c
.RI "void \fBset\fP (signed int value)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Turn a conveyor ON or OFF\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConveyorActuatorBinary::ConveyorActuatorBinary (intid, \fBConveyor\fP *conveyor)"

.SH "Member Function Documentation"
.PP 
.SS "void ConveyorActuatorBinary::set (signed intvalue)\fC [virtual]\fP"

.PP
Reimplemented from \fBConveyorActuator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
