.TH "JointActuatorRevoluteStep" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JointActuatorRevoluteStep \- 
.PP
Turn a revolute joint an arbitrary angle\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Actuators\&.h>\fP
.PP
Inherits \fBActuator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJointActuatorRevoluteStep\fP (int id, b2Joint *joint)"
.br
.ti -1c
.RI "void \fBset\fP (signed int value)"
.br
.ti -1c
.RI "void \fBdrawLabel\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "b2Joint * \fBm_joint\fP"
.br
.ti -1c
.RI "float32 \fBm_startAngle\fP"
.br
.ti -1c
.RI "float32 \fBm_currentAngle\fP"
.br
.ti -1c
.RI "float32 \fBm_maxRotation\fP"
.br
.ti -1c
.RI "signed int \fBm_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Turn a revolute joint an arbitrary angle\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JointActuatorRevoluteStep::JointActuatorRevoluteStep (intid, b2Joint *joint)"

.SH "Member Function Documentation"
.PP 
.SS "void JointActuatorRevoluteStep::drawLabel ()\fC [virtual]\fP"

.PP
Reimplemented from \fBActuator\fP\&.
.SS "void JointActuatorRevoluteStep::run ()\fC [virtual]\fP"

.PP
Reimplemented from \fBActuator\fP\&.
.SS "void JointActuatorRevoluteStep::set (signed intvalue)\fC [virtual]\fP"

.PP
Reimplemented from \fBActuator\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float32 JointActuatorRevoluteStep::m_currentAngle"

.SS "b2Joint* JointActuatorRevoluteStep::m_joint"

.SS "float32 JointActuatorRevoluteStep::m_maxRotation"

.SS "float32 JointActuatorRevoluteStep::m_startAngle"

.SS "signed int JointActuatorRevoluteStep::m_value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
