.TH "JointActuatorPrismaticRange" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JointActuatorPrismaticRange \- 
.PP
Run a prismatic joint at an arbitrary constant speed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Actuators\&.h>\fP
.PP
Inherits \fBActuator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJointActuatorPrismaticRange\fP (int id, b2Joint *joint)"
.br
.ti -1c
.RI "void \fBset\fP (signed int value)"
.br
.ti -1c
.RI "void \fBdrawLabel\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "b2Joint * \fBm_joint\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Run a prismatic joint at an arbitrary constant speed\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JointActuatorPrismaticRange::JointActuatorPrismaticRange (intid, b2Joint *joint)"

.SH "Member Function Documentation"
.PP 
.SS "void JointActuatorPrismaticRange::drawLabel ()\fC [virtual]\fP"

.PP
Reimplemented from \fBActuator\fP\&.
.SS "void JointActuatorPrismaticRange::set (signed intvalue)\fC [virtual]\fP"

.PP
Reimplemented from \fBActuator\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "b2Joint* JointActuatorPrismaticRange::m_joint"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
