.TH "LengthSensor" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LengthSensor \- 
.PP
Measure length of a colliding Plank-instance\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sensors\&.h>\fP
.PP
Inherits \fBContactSensorBinary\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLengthSensor\fP (int id, b2Vec2 position, float32 radius, b2World *world)"
.br
.ti -1c
.RI "void \fBmeassureLength\fP (float32 length)"
.br
.ti -1c
.RI "signed int \fBget\fP ()"
.br
.RI "\fIReturn the state of the sensor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "signed int \fBm_meassuredLenght\fP"
.br
.RI "\fIStore the last measured plank length\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Measure length of a colliding Plank-instance\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LengthSensor::LengthSensor (intid, b2Vec2position, float32radius, b2World *world)"

.SH "Member Function Documentation"
.PP 
.SS "signed int LengthSensor::get ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Return the state of the sensor\&. 
.PP
Reimplemented from \fBContactSensorBinary\fP\&.
.SS "void LengthSensor::meassureLength (float32length)"

.SH "Member Data Documentation"
.PP 
.SS "signed int LengthSensor::m_meassuredLenght"

.PP
Store the last measured plank length\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
