.TH "Main.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main.h \- 
.PP
\fBMain\&.h\fP and \fBMain\&.cpp\fP contains the main-function, and code to create user-interface and run the simulation-loop\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'glui/glui\&.h'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'Communicator\&.h'\fP
.br
\fC#include 'Render\&.h'\fP
.br
\fC#include 'SimulatorPage\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMain\&.h\fP and \fBMain\&.cpp\fP contains the main-function, and code to create user-interface and run the simulation-loop\&. 

, Based on Erin Cattos Box2D 2\&.2\&.1 Testbed \fBMain\&.cpp\fP 
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"
Start program execution 
.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
