.TH "md_README" 3 "Sun Dec 9 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- README {} 
.SS "Configuration instructions"
.PP
.SS "Installation instructions"
.PP
.SS "Operating instructions"
.PP
.SS "Example:"
.PP
.SS "File manifest"
.PP
-doc/ This folder contains the project documentation\&. -Main\&.cpp Create the GUI -Render\&.cpp -Render\&.h -SimulatorPage\&.cpp -SimulatorPage\&.h -PlankSortingPlant\&.cpp -PlankSortingPlant\&.h -SimulatorPageEntries\&.cpp -Actuators\&.cpp -Actuators\&.h -Communicator\&.cpp -Communicator\&.h -CommandSequenceInterpreter\&.cpp -CommandSequenceInterpreter\&.h -Conveyor\&.cpp -Conveyor\&.h -ConveyorSynchronizer\&.cpp -ConveyorSynchronizer\&.h -Package\&.cpp -Package\&.h -Packaging\&.cpp -Packaging\&.h -Sensors\&.cpp -Sensors\&.h -Storages\&.cpp -Storages\&.h -Text\&.h -Text\&.cpp -UserData\&.cpp -UserData\&.h
.PP
.SS "Copyright and licensing information"
.PP
.SS "Contact information for the distributor or programmer"
.PP
.SS "Known bugs[1]"
.PP
.SS "Troubleshooting[1]"
.PP
.SS "Credits and acknowledgments"
.PP
.SS "Changelog"
.PP
\&.\&.\&.
.PP
.SS "News"
.PP
\&.\&.\&. 
