.TH "MedbringerkUserData" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MedbringerkUserData \- 
.PP
Identify a b2Fixture as a 'medbringer'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UserData\&.h>\fP
.PP
Inherits \fBUserData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMedbringerkUserData\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Identify a b2Fixture as a 'medbringer'\&. 

Each 'medbringers' b2Fixture points to an instance of this class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MedbringerkUserData::MedbringerkUserData ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
