.TH "Packaging.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Packaging.h \- 
.PP
Contains the PackageInput- and PackageOutput-class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Box2D/Box2D\&.h>\fP
.br
\fC#include 'Package\&.h'\fP
.br
\fC#include 'UserData\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPackageInput\fP"
.br
.RI "\fIRepresent the package input block\&. \fP"
.ti -1c
.RI "class \fBPackageOutput\fP"
.br
.RI "\fIRepresent the package output block\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains the PackageInput- and PackageOutput-class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
