.TH "Package.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Package.h \- 
.PP
Contains the classes related to planks, 'sprinkles' and packages\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'UserData\&.h'\fP
.br
\fC#include <Box2D/Box2D\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSprinkle\fP"
.br
.RI "\fIRepresent 'Sprinkle'-objects(In norwegian: strø)\&. \fP"
.ti -1c
.RI "class \fBPlank\fP"
.br
.RI "\fIRepresent Plank-objects\&. \fP"
.ti -1c
.RI "class \fBPackage\fP"
.br
.RI "\fIRepresent Package-objects\&. \fP"
.ti -1c
.RI "class \fBSprinkleSource\fP"
.br
.RI "\fILets you create and destruct sprinkles by id\&. \fP"
.ti -1c
.RI "class \fBPackageSource\fP"
.br
.RI "\fILets you create and destruct packages by id\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains the classes related to planks, 'sprinkles' and packages\&. 

\fBAuthor:\fP
.RS 4
Roy Kollen Svendsen 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
