.TH "PlankUserData" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlankUserData \- 
.PP
Carry information about planks\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UserData\&.h>\fP
.PP
Inherits \fBUserData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlankUserData\fP (float32 length, float32 quality)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float32 \fBm_length\fP"
.br
.ti -1c
.RI "float32 \fBm_quality\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Carry information about planks\&. 

Each planks b2Fixture points to an instance of this class\&. Contains information about a planks objective length and planks objective quality\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlankUserData::PlankUserData (float32length, float32quality)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float32 PlankUserData::m_length"

.SS "float32 PlankUserData::m_quality"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
