.TH "PlankSortingPlant.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlankSortingPlant.h \- 
.PP
Contains the SimulationPage to create a 'plank sorting plant'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Conveyor\&.h'\fP
.br
\fC#include 'ConveyorSynchronizer\&.h'\fP
.br
\fC#include 'Storages\&.h'\fP
.br
\fC#include 'Actuators\&.h'\fP
.br
\fC#include 'Sensors\&.h'\fP
.br
\fC#include 'Packaging\&.h'\fP
.br
\fC#include 'Communicator\&.h'\fP
.br
\fC#include 'CommandSequenceInterpreter\&.h'\fP
.br
\fC#include 'SimulatorPage\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlankSortingPlant\fP"
.br
.RI "\fIExtend the default \fBSimulatorPage\fP to create a simulation of a plank sorting plant\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains the SimulationPage to create a 'plank sorting plant'\&. 

\fBAuthor:\fP
.RS 4
Roy Kollen Svendsen 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
