.TH "QueryCallback" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueryCallback \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits b2QueryCallback\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueryCallback\fP (const b2Vec2 &point)"
.br
.ti -1c
.RI "bool \fBReportFixture\fP (b2Fixture *fixture)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "b2Vec2 \fBm_point\fP"
.br
.ti -1c
.RI "b2Fixture * \fBm_fixture\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QueryCallback::QueryCallback (const b2Vec2 &point)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool QueryCallback::ReportFixture (b2Fixture *fixture)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "b2Fixture* QueryCallback::m_fixture"

.SS "b2Vec2 QueryCallback::m_point"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
