.TH "Render.cpp" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Render.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Render\&.h'\fP
.br
\fC#include 'freeglut/freeglut\&.h'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstdarg>\fP
.br
\fC#include <cstring>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
