.TH "Settings" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Settings \- 
.PP
\fBSimulatorPage\fP settings\&. Some can be controlled in the GUI\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimulatorPage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSettings\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "b2Vec2 \fBviewCenter\fP"
.br
.ti -1c
.RI "float32 \fBhz\fP"
.br
.ti -1c
.RI "int32 \fBvelocityIterations\fP"
.br
.ti -1c
.RI "int32 \fBpositionIterations\fP"
.br
.ti -1c
.RI "int32 \fBdrawShapes\fP"
.br
.ti -1c
.RI "int32 \fBdrawJoints\fP"
.br
.ti -1c
.RI "int32 \fBdrawAABBs\fP"
.br
.ti -1c
.RI "int32 \fBdrawPairs\fP"
.br
.ti -1c
.RI "int32 \fBdrawContactPoints\fP"
.br
.ti -1c
.RI "int32 \fBdrawContactNormals\fP"
.br
.ti -1c
.RI "int32 \fBdrawContactForces\fP"
.br
.ti -1c
.RI "int32 \fBdrawFrictionForces\fP"
.br
.ti -1c
.RI "int32 \fBdrawCOMs\fP"
.br
.ti -1c
.RI "int32 \fBdrawStats\fP"
.br
.ti -1c
.RI "int32 \fBdrawProfile\fP"
.br
.ti -1c
.RI "int32 \fBenableWarmStarting\fP"
.br
.ti -1c
.RI "int32 \fBenableContinuous\fP"
.br
.ti -1c
.RI "int32 \fBenableSubStepping\fP"
.br
.ti -1c
.RI "int32 \fBpause\fP"
.br
.ti -1c
.RI "int32 \fBsingleStep\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSimulatorPage\fP settings\&. Some can be controlled in the GUI\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Settings::Settings ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int32 Settings::drawAABBs"

.SS "int32 Settings::drawCOMs"

.SS "int32 Settings::drawContactForces"

.SS "int32 Settings::drawContactNormals"

.SS "int32 Settings::drawContactPoints"

.SS "int32 Settings::drawFrictionForces"

.SS "int32 Settings::drawJoints"

.SS "int32 Settings::drawPairs"

.SS "int32 Settings::drawProfile"

.SS "int32 Settings::drawShapes"

.SS "int32 Settings::drawStats"

.SS "int32 Settings::enableContinuous"

.SS "int32 Settings::enableSubStepping"

.SS "int32 Settings::enableWarmStarting"

.SS "float32 Settings::hz"

.SS "int32 Settings::pause"

.SS "int32 Settings::positionIterations"

.SS "int32 Settings::singleStep"

.SS "int32 Settings::velocityIterations"

.SS "b2Vec2 Settings::viewCenter"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
