.TH "SimulatorPageEntry" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimulatorPageEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimulatorPage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBSimulatorPageCreateFcn\fP * \fBcreateFcn\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBSimulatorPageCreateFcn\fP* SimulatorPageEntry::createFcn"

.SS "const char* SimulatorPageEntry::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
