.TH "SimulatorPage.cpp" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimulatorPage.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SimulatorPage\&.h'\fP
.br
\fC#include <cstdio>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQueryCallback\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
