.TH "Storages.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Storages.h \- 
.PP
Define classes to create individual storages and storage area\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Box2D/Box2D\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'UserData\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStorage\fP"
.br
.RI "\fICreate an individual storage to sort planks into\&. \fP"
.ti -1c
.RI "class \fBStorageArea\fP"
.br
.RI "\fICreate an arbitrary number of storages side-by-side to sort planks into\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Define classes to create individual storages and storage area\&. 

\fBAuthor:\fP
.RS 4
Roy Kollen Svendsen 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
