.TH "Text.h" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Text.h \- 
.PP
Contains a function to draw text on \fBSimulatorPage\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Box2D/Box2D\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'freeglut/freeglut\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdrawStrokeText\fP (string str, b2Vec2 position, float32 size, b2Color color)"
.br
.RI "\fIDraw string on current \fBSimulatorPage\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains a function to draw text on \fBSimulatorPage\fP\&. 

\fBAuthor:\fP
.RS 4
Roy Kollen Svendsen 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void drawStrokeText (stringstr, b2Vec2position, float32size, b2Colorcolor)"

.PP
Draw string on current \fBSimulatorPage\fP\&. \fBParameters:\fP
.RS 4
\fIstr\fP The string you want to display\&. 
.br
\fIposition\fP The lower left corner of the string\&. 
.br
\fIsize\fP A factor that changes the dimensions of the string\&. 
.br
\fIcolor\fP The text-color\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
