.TH "UserData" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserData \- 
.PP
The archtypical userdata-class which other userdata-classes inherit from\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UserData\&.h>\fP
.PP
Inherited by \fBMedbringerkUserData\fP\fC [private]\fP, \fBPlankUserData\fP\fC [private]\fP, and \fBStorageLiftUserData\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBt_userDataType\fP \fBm_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The archtypical userdata-class which other userdata-classes inherit from\&. 

These common features makes handling user-data much simpler\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UserData::UserData ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBt_userDataType\fP UserData::m_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
