.TH "Wheel" 3 "Wed Dec 12 2012" "Version 1.0" "Educational simulator for control-system development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Wheel \- 
.PP
The conveyors wheels\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Conveyor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWheel\fP (b2Vec2 p, float32 r, int cmBits, b2World *world)"
.br
.ti -1c
.RI "void \fBsetSpeed\fP (float32 speed)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "b2Body * \fBgetBody\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "b2Body * \fBm_body\fP"
.br
.ti -1c
.RI "float32 \fBm_speed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The conveyors wheels\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Wheel::Wheel (b2Vec2p, float32r, intcmBits, b2World *world)"

.SH "Member Function Documentation"
.PP 
.SS "b2Body* Wheel::getBody ()\fC [inline]\fP"

.SS "void Wheel::run ()"

.SS "void Wheel::setSpeed (float32speed)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "b2Body* Wheel::m_body\fC [private]\fP"

.SS "float32 Wheel::m_speed\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Educational simulator for control-system development from the source code\&.
